let actionTypes = {
    LOGIN_ERROR:'LOGIN_ERROR',
    LOGIN_ERROR_CLOSE:'LOGIN_ERROR_CLOSE',
    LOADER_OPEN:'LOADER_OPEN',
    LOADER_CLOSE:'LOADER_CLOSE',

    SAVE_UID:'SAVE_UID',

    REGISTER_DONOR:'REGISTER_DONOR',
    REGISTRATION_LOADER_OPEN:'REGISTRATION_LOADER_OPEN',
    REGISTRATION_LOADER_CLOSE:'REGISTRATION_LOADER_CLOSE',

    EDIT_PROFILE:'EDIT_PROFILE',
    UPDATE_PROFILE:'UPDATE_PROFILE',
    CANCEL_UPDATION:'CANCEL_UPDATION',

    GET_DATA:'GET_DATA',

} 
export default actionTypes