let actionTypes = {
    LOGIN_ERROR:'LOGIN_ERROR',
    LOGIN_ERROR_CLOSE:'LOGIN_ERROR_CLOSE',
    LOADER_OPEN:'LOADER_OPEN',
    LOADER_CLOSE:'LOADER_CLOSE',

    SAVE_UID:'SAVE_UID',

    REGISTRATION:'REGISTRATION',
    REGISTER_DONOR:'REGISTER_DONOR',
    REGISTRATION_LOADER_OPEN:'REGISTRATION_LOADER_OPEN',
    REGISTRATION_LOADER_CLOSE:'REGISTRATION_LOADER_CLOSE',
    UNREGISTERED:'UNREGISTERED',

    EDIT_PROFILE:'EDIT_PROFILE',
    UPDATE_PROFILE:'UPDATE_PROFILE',
    CANCEL_UPDATION:'CANCEL_UPDATION',
    OLD_PROFILE:'OLD_PROFILE',

    GET_DONORS:'GET_DONORS',

    REQUEST:'REQUEST',
    CANCEL_REQUEST:'CANCEL_REQUEST',
    ACCEPT_REQUEST:'ACCEPT_REQUEST',
    IGNORE_REQUEST:'IGNORE_REQUEST'

} 
export default actionTypes