let actionTypes = {

    LOGIN_ERROR:'LOGIN_ERROR',
    LOGIN_ERROR_CLOSE:'LOGIN_ERROR_CLOSE',
    LOADER_OPEN:'LOADER_OPEN',
    LOADER_CLOSE:'LOADER_CLOSE',

    SAVE_UID:'SAVE_UID',

    REGISTRATION:'REGISTRATION',
    REGISTER_DONOR:'REGISTER_DONOR',
    REGISTRATION_LOADER_OPEN:'REGISTRATION_LOADER_OPEN',
    REGISTRATION_LOADER_CLOSE:'REGISTRATION_LOADER_CLOSE',
    UNREGISTERED:'UNREGISTERED',

    GET_PROFILE:'GET_PROFILE',
    PROFILE_LOADER_OPEN:'PROFILE_LOADER_OPEN',
    PROFILE_LOADER_CLOSE:'PROFILE_LOADER_CLOSE',
    

    EDIT_PROFILE:'EDIT_PROFILE',

    UPDATE_PROFILE:'UPDATE_PROFILE',
    UPDATE_LOADER_OPEN:'UPDATE_LOADER_OPEN',
    UPDATE_LOADER_CLOSE:'UPDATE_LOADER_CLOSE',
    CANCEL_UPDATION:'CANCEL_UPDATION', 
    

    GET_DONORS:'GET_DONORS',
    REMOVE_DONORS:'REMOVE_DONORS',

    GET_REQUESTS:'GET_REQUESTS',
    
    CHECK_REQUESTS:'CHECK_REQUEST',
    REQUEST_LOADER_OPEN:'REQUEST_LOADER_OPEN',
    REQUEST_LOADER_CLOSE:'REQUEST_LOADER_CLOSE',
    REQUEST_LOADERS_EMPTY:'REQUEST_LOADERS_EMPTY',

    CANCEL_REQUEST:'CANCEL_REQUEST',
    CANCEL_LOADER_OPEN:'CANCEL_LOADER_OPEN',
    CANCEL_LOADER_CLOSE:'CANCEL_LOADER_CLOSE',

    ACCEPT_REQUEST:'ACCEPT_REQUEST',
    ACCEPT_LOADER_OPEN:'ACCEPT_LOADER_OPEN',
    ACCEPT_LOADER_CLOSE:'ACCEPT_LOADER_CLOSE',

    IGNORE_REQUEST:'IGNORE_REQUEST',
    IGNORE_LOADER_OPEN:'IGNORE_LOADER_OPEN',
    IGNORE_LOADER_CLOSE:'IGNORE_LOADER_CLOSE',

    GET_NOTIFICATIONS:'GET_NOTIFICATIONS',
    NOTIFICATION_LOADER_OPEN:'NOTIFICATION_LOADER_OPEN',
    NOTIFICATION_LOADER_CLOSE:'NOTIFICATION_LOADER_CLOSE',


} 
export default actionTypes